---

# Travis file for {{ cookiecutter.ansible_role_name }} role

dist: trusty
sudo: required

services:
  - docker

language: 'python'

python:
  - '2.7'

env:
  global:
    - ANSIBLE_ROLES_PATH="${TRAVIS_BUILD_DIR%/*/*}"

  matrix:
    - TOXENV='py27-ansible19'
    - TOXENV='py27-ansible20'
    - TOXENV='py27-ansible21'
    - TOXENV='py27-ansible-devel'

before_install:

  # Create SSH keys
  -  cat /dev/zero | ssh-keygen -q -N ""
install:

  # Install tox dependency
  - 'pip install tox'

script:

  # Run tests
  - 'make test-env'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
