---

# Airflow installation tasks

# Manage system dependencies
- name: 'INSTALL | Manage system dependencies'
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ airflow_system_dependencies }}"


# Create user
- name: 'INSTALL | Manage airflow user creation'
  user:
    name: "{{ airflow_user_name }}"
    createhome: True
    home: "{{ airflow_user_home_path}}"
    state: 'present'
    shell: "{{ airflow_user_shell }}"


- name: 'INSTALL | Manage permissions on user home directory'
  file:
    path: "{{ airflow_user_home_path }}"
    owner: "{{ airflow_user_name }}"
    group: "{{ airflow_user_name }}"
    mode: "{{ airflow_user_home_mode }}"


# Install airflow packages
- name: 'INSTALL | Manage airflow installation'
  become_user: "{{ airflow_user_name }}"
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    virtualenv: "{{ airflow_virtualenv }}"
    virtualenv_python: "{{ airflow_python_version }}"
  changed_when: "airflow_pip_changed_when"
  with_items: "{{ airflow_packages }}"


# Install airflow extra packages
- name: 'INSTALL | Manage airflow extra packages installation'
  become_user: "{{ airflow_user_name }}"
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    virtualenv: "{{ airflow_virtualenv }}"
    virtualenv_python: "{{ airflow_python_version }}"
  changed_when: "airflow_pip_changed_when"
  with_items: "{{ airflow_extra_packages }}"
