---

# Airflow installation tasks

# Manage system dependencies
- name: 'INSTALL | Manage system dependencies'
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ airflow_system_dependencies }}"


# Create user
- name: 'INSTALL | Manage airflow user creation'
  user:
    name: "{{ airflow_user_name }}"
    createhome: True
    home: "{{ airflow_user_home_path}}"
    state: 'present'
    shell: "{{ airflow_user_shell }}"


# Check if configuration file exists
# This has to happen before the install, because the install creates a default file in $AIRFLOW_HOME
- name: 'INSTALL | Check if configuration file exists'
  stat:
    path: "{{ airflow_config.core.airflow_home }}/airflow.cfg"
  register: 'airflow_config_stat'
  changed_when: False


- name: 'INSTALL | Manage permissions on user home directory'
  file:
    path: "{{ airflow_user_home_path }}"
    owner: "{{ airflow_user_name }}"
    group: "{{ airflow_user_name }}"
    mode: "{{ airflow_user_home_mode }}"
    state: directory


- name: 'INSTALL | Manage permissions on airflow venv directory'
  file:
    path: "{{ airflow_virtualenv }}"
    owner: "{{ airflow_user_name }}"
    group: "{{ airflow_user_name }}"
    mode: "{{ airflow_virtualenv_mode }}"
    state: directory

- name: 'INSTALL | Manage permissions on airflow home directory'
  file:
    path: "{{ airflow_config.core.airflow_home }}"
    owner: "{{ airflow_user_name }}"
    group: "{{ airflow_user_name }}"
    mode: "{{ airflow_config.core.airflow_home_mode }}"
    state: directory


- name: 'INSTALL | Manage permissions on airflow dags directory'
  file:
    path: "{{ airflow_config.core.dags_folder }}"
    owner: "{{ airflow_user_name }}"
    group: "{{ airflow_user_name }}"
    mode: "{{ airflow_config.core.dags_folder_mode }}"
    state: directory


# setup environment for all users, AIRFLOW_HOME, etc
- name: 'INSTALL | Manage /etc/profile.d/ file'
  template:
    src: "{{ role_path }}/templates/airflow.profile.j2"
    dest: "/etc/profile.d/airflow.sh"
  when: airflow_provide_user_env


# Install airflow packages
- name: 'INSTALL | Manage airflow installation'
  become_user: "{{ airflow_user_name }}"
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    virtualenv: "{{ airflow_virtualenv }}"
    virtualenv_python: "{{ airflow_python_version }}"
  changed_when: "airflow_pip_changed_when"
  with_items: "{{ airflow_packages }}"


# Install airflow extra packages
- name: 'INSTALL | Manage airflow extra packages installation'
  become_user: "{{ airflow_user_name }}"
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    virtualenv: "{{ airflow_virtualenv }}"
    virtualenv_python: "{{ airflow_python_version }}"
  changed_when: "airflow_pip_changed_when"
  with_items: "{{ airflow_extra_packages }}"
