---

# Handlers main file for airflow role

- name: 'Restart airflow'
  become: True
  service:
    name: "{{ item.name }}"
    state: 'restarted'
  with_items: "{{ airflow_services_states }}"
  when: "item.state == 'started'"
  tags:
    - 'role::airflow'
    - 'role::airflow::config'
    - 'role::airflow::install'


- name: 'Restart airflow-webserver'
  become: True
  service:
    name: "{{ item.name }}"
    state: 'restarted'
  with_items: "{{ airflow_services_states }}"
  when:
    - "item.name == 'airflow-webserver'"
    - "item.state == 'started'"
  tags:
    - 'role::airflow'
    - 'role::airflow::config'
    - 'role::airflow::install'


- name: 'Restart airflow-scheduler'
  become: True
  service:
    name: "{{ item.name }}"
    state: 'restarted'
  with_items: "{{ airflow_services_states }}"
  when:
    - "item.name == 'airflow-scheduler'"
    - "item.state == 'started'"
  tags:
    - 'role::airflow'
    - 'role::airflow::config'
    - 'role::airflow::install'
